import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const MonoMitra = localFont({
  src: "./fonts/BMitra.ttf",
  variable: "--font-mitra-mono",
  weight: "100 500",
});
const BoldMitra = localFont({
  src: "./fonts/BMitraBold.ttf",
  variable: "--font-mitra-bold",
  weight: "500 900",
});

export const metadata: Metadata = {
  title: "نوبت دهی",
  description: "Generated by Wexen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BoldMitra.variable} ${MonoMitra.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
